name: Archive

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  archive:
    runs-on: windows-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          path: arch
          ref: archive
          
      - name: Run Script
        run: |
          $ErrorActionPreference= 'silentlycontinue'
          .\archive.ps1
          mv *.csv arch/ 
          cd arch/
          ..\merge.ps1
          cd ..
          ls
          ls arch/

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: 'archive'
          repository: 'arch'
          skip_dirty_check: true
