name: Pages-Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Make dir
        run: mkdir public

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Talan igy?" >> ./public/index.html

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Get PS version
        run: $PSVersionTable.PSVersion
          
      - name: ls
        run: ls
        shell: powershell
          
      - name: do gettypes
        run: |
          .\getTypes.ps1 'https://www.arukereso.hu' 'videokartya-c3142' 5 > ./public/index.html
          
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
