name: Refresh Pages

on:
  push:
    branches: [ archive ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          path: arch
          ref: archive
          
      - run: mkdir public
        
      - run: |
          cd arch\
          ..\generateHTML.ps1
          mv *.html ..\public
          
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
