name: Refresh Pages

on:
  push:
    branches: [ archive ]
  workflow_dispatch:
  workflow_run:
    workflows: ["Archive"]
    types:
      - completed
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          path: arch
          ref: archive
      - uses: actions/checkout@v2
        with:
          path: public
          ref: gh-pages
                
      - run: |
          cd arch\
          ..\generateHTML.ps1
          mv *.html ..\public -Force
          cd ..
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: 'gh-pages'
          repository: 'public'
          skip_dirty_check: true
